### ISSUE TITLE
Improve privacy and UX for giving feedback

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#77]
Currently winden.app use feedback form based on Wordpress form in Least Authority page: https://leastauthority.com/winden-feedback/. We have less control on what is collected over LA page and wpengine.com.

To improve privacy and to have control what data we are not collecting in winden.app, we need to create internal feedback backend, which can receive content form webpage and send data to internal email with no information collected.

Initial work-in-progress repo: https://github.com/LeastAuthority/feedback-api 

Additionally to this, we can improve feedback UI not only requesting under Feedback button at the bottom, but also allowing users rate and leave comment after each transfer (not intrusive). This should increase success rate of getting any feedback.

**Note**: internal task: #OP2291, #OP2280, and frontend part: #OP2292

**Tasks:**

- [x] Create Feedback API where data could be pushed and emailed later on: https://github.com/LeastAuthority/feedback-api/issues/2; 
- [x] Create Feedback [page](https://winden.app/feedback) with integrated new form: https://github.com/LeastAuthority/winden/issues/118
- [x] Deploy Feedback API in stage env: https://github.com/LeastAuthority/mw-projects/issues/83
- [ ] Deploy Winden Feedback changes to stage env. and connect with stage feedback-api server;
- [ ] Perform tests on stage env. for feedback-api functionality and check if mail is received in Google mailbox;
- [ ] Deploy Winden Feedback and Feedback-api to production server;
- [ ] Verify if feedback is received in contact@winden.app mailbox;

**Optional tasks:**
- [ ] Find new ways to encourage getting feedback straight after Send/Receive completion: https://github.com/LeastAuthority/winden/issues/119
- [ ] Remove old feedback page: https://leastauthority.com/winden-feedback/

**Comment by btlogy** [comment]
I believe most of the subtasasks in the description of this issue can be ticked since #124 has been merged.
Am I right @JustusFT ?

Do we still need to remove something to close this one?

**Comment by JustusFT** [comment]
Yes, we can close this one :+1:
